### ISSUE TITLE
how should I use this library

### ISSUE THREAD

**Issue by aimuz** [einride/iam-go#336]
```
syntax = "proto3";

package feedback.v1;

import "einride/iam/v1/annotations.proto";
import "google/api/annotations.proto";
import "google/api/client.proto";
import "google/api/field_behavior.proto";
import "google/api/resource.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/field_mask.proto";
import "google/protobuf/timestamp.proto";

option go_package = "example/genproto/feedback/v1;feedbackv1";

service FeedbackService {
  // GetFeedback ....
  rpc GetFeedback(GetFeedbackRequest) returns (Feedback) {
    option (google.api.http) = {
      get: "/v1/{name=users/*/feedbacks/*}",
    };
    option (google.api.method_signature) = "name";
    option (einride.iam.v1.method_authorization) = {
      permission: "example.feedbacks.get"
      before {
        expression: "test(caller, request.name)"
        description: "The caller must have permission to get the feedbacks."
      }
    };
  }
}
```

```
version: v1
name: buf.build/example/api
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
  - buf.build/einride/iam
lint:
  use:
    - DEFAULT
  except:
    - RPC_RESPONSE_STANDARD_NAME
    - RPC_REQUEST_RESPONSE_UNIQUE
  rpc_allow_google_protobuf_empty_requests: true
  rpc_allow_google_protobuf_empty_responses: true
```

I tried to build via buf and got an error

```zsh
$ buf generate
protoc-gen-go-grpc: unable to determine Go import path for "einride/iam/v1/annotations.proto"

Please specify either:
        • a "go_package" option in the .proto source file, or
        • a "M" argument on the command line.

See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

Failure: plugin go-grpc: exit status 1; signal: killed

```

Try adding the following to buf.gen.yaml

```
version: v1
managed:
  enabled: true
  go_package_prefix:
    default: example/genproto
    except:
      - buf.build/googleapis/googleapis
```

Execute `buf generate` successfully

But there is a new problem with go build, the relevant package is not found

```
$ go build ./cmd/apiserver 
genproto/feedback/v1/feedback.pb.go:10:2: package example/genproto/einride/iam/v1 is not in GOROOT (/usr/local/opt/go/libexec/src/example/genproto/einride/iam/v1)

```
